project:
  type: website
website:
  title: "Una introducción a GAP"
  search: false
  site-url: https://pedritomelenas.github.io/Software-Matematicas-GAP/
  repo-url: https://github.com/pedritomelenas/Software-Matematicas-GAP
  issue-url: https://github.com/pedritomelenas/Software-Matematicas-GAP/issues
  navbar:
    right:
      - icon: github
        href: https://github.com/pedritomelenas/Software-Matematicas-GAP
        aria-label: GitHub

  sidebar: 
    style: "docked"
    footer: Hecho con [Quarto](https://quarto.org/)
    contents:
      - text: "Primeros pasos"
        href: "1 Primeros pasos.ipynb"
      - text: "Aritmética entera y modular"
        href: "2 Aritmetica entera y modular.ipynb"
      - text: "Enteros de Gauss"
        href: "3 Enteros de Gauss.ipynb"
      - text: "Combinatoria"
        href: "4 Combinatoria.ipynb"
      - text: "Conjuntos, relaciones y funciones"
        href: "5 Conjuntos relaciones funciones.ipynb"
      - text: "Polinomios"
        href: "6 Polinomios.ipynb"
      - text: "Matrices y espacios vectoriales"
        href: "7 Matrices-espacios-vectoriales.ipynb"
      - text: "Visualización"
        href: "8 Visualizacion en jupyter y gap.ipynb"
      - text: "Objetos"
        href: "9 Creando nuevos objetos.ipynb"

format:
  html:
    theme: cosmo
    lang: es